require("options")
require("mappings")
require("autocmds")
require("lsp")
require("plugins")
require("commands")
require("ui.statusline").setup()
require("ui.tabline").setup()

vim.cmd.colorscheme("retrobox")
